Update conexao

diff --git a/Modulos/conexao b/Modulos/conexao
--- a/Modulos/conexao
+++ b/Modulos/conexao
@@ -1568,9 +1568,9 @@ exit 0' >$RCLOCAL
 				echo -e "\033[1;32mSOCKS ATIVADO COM SUCESSO\033[1;33m"
 				sleep 3
 				fun_socks
-			fi
-        elif [[ "$resposta" = '2' ]]; then
-			if ps x | grep -w wsproxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
+			 fi
+                elif [[ "$resposta" = '2' ]]; then
+			 if ps x | grep -w wsproxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
 				clear
 				echo -e "\E[41;1;37m             WEBSOCKET              \E[0m"
 				echo ""
@@ -1623,9 +1623,62 @@ exit 0' >$RCLOCAL
 				echo -e "\033[1;32WSSOCKS ATIVADO COM SUCESSO\033[1;33m"
 				sleep 3
 				fun_socks
+		       fi
+               elif [[ "$resposta" = '3' ]]; then
+		       clear
+		       if ps x | grep -w WebSocket | grep -v grep 1>/dev/null 2>/dev/null; then
+		               echo -e "\E[41;1;37m          WEBSOCKET SECURITY              \E[0m"
+			       echo ""
+			       fun_wsswsocksoff() { 
+					pkill WebSocket
+					for pidproxy in $(screen -ls | grep ".ws" | awk {'print $1'}); do
+						screen -r -S "$WebSocket" -X quit
+					done
+					[[ $(grep -wc "WebSocket" /etc/autostart) != '0' ]] && {
+						sed -i '/WebSocket/d' /etc/autostart
+					}
+					sleep 1
+					screen -wipe >/dev/null
+				}
+				echo -e "\033[1;32mDESATIVANDO O WEBSOCKET SECURITY\033[1;33m"
+				echo ""
+				fun_bar 'fun_wsswsocksoff'
+				echo ""
+				echo -e "\033[1;32mWEBSOCKET SECURITY DESATIVADO COM SUCESSO!\033[1;33m"
+				
+				fun_socks
+			else
+		                echo -e "\E[44;1;37m          WEBSOCKET SECURITY              \E[0m"
+				echo ""
+				echo "$(echo -e "\033[1;32mPORTA UTILIZADA 80 \033[1;37m")"
+				[[ -z "porta" ]] && {
+					echo ""
+					echo -e "\033[1;31mPorta invalida!"
+					
+				fun_socks
+				}
+				verif_ptrs $porta
+				fun_iniwssocks() {
+					sleep 1
+					screen -dmS novoWS /etc/SSHPlus/WebSocket 
+					[[ $(grep -wc "WebSocket" /etc/autostart) = '0' ]] && {
+						echo -e "screen -dmS novoWS /etc/SSHPlus/WebSocket -proxy_port 0.0.0.0:8080" >>/etc/autostart
+					} || {
+						sed -i '/WebSocket/d' /etc/autostart
+						echo -e "screen -dmS novoWS /etc/SSHPlus/WebSocket -proxy_port 0.0.0.0:8080" >>/etc/autostart
+					}
+				}
+				echo ""
+				echo -e "\033[1;32mINICIANDO O WEBSOCKET SECURITY\033[1;33m"
+				echo ""
+				fun_bar 'fun_iniwssocks'
+				echo ""
+				echo -e "\033[1;32WEBSOCKET SECURITY ATIVADO COM SUCESSO\033[1;33m"
+				
+				fun_socks
 			fi
-		elif [[ "$resposta" = '3' ]]; then
-			if ps x | grep -w open.py | grep -v grep 1>/dev/null 2>/dev/null; then
+		elif [[ "$resposta" = '4' ]]; then
+		        if ps x | grep -w open.py | grep -v grep 1>/dev/null 2>/dev/null; then
 				clear
 				echo -e "\E[41;1;37m            SOCKS OPENVPN             \E[0m"
 				echo ""
@@ -1684,8 +1737,8 @@ exit 0' >$RCLOCAL
 				sleep 3
 				fun_socks
 			fi
-		elif [[ "$resposta" = '4' ]]; then
-			if ps x | grep proxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
+		elif [[ "$resposta" = '5' ]]; then
+		        if ps x | grep proxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
 				sockspt=$(netstat -nplt | grep 'python' | awk {'print $4'} | cut -d: -f2 | xargs)
 				clear
 				echo -e "\E[44;1;37m            PROXY SOCKS             \E[0m"
@@ -1721,7 +1774,7 @@ exit 0' >$RCLOCAL
 				sleep 2
 				fun_socks
 			fi
-		elif [[ "$resposta" = '5' ]]; then
+		elif [[ "$resposta" = '6' ]]; then
 			if ps x | grep -w proxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
 				clear
 				msgsocks=$(cat /etc/SSHPlus/proxy.py | grep -E "MSG =" | awk -F = '{print $2}' | cut -d "'" -f 2)
@@ -1816,7 +1869,7 @@ exit 0' >$RCLOCAL
 				sleep 2
 				fun_socks
 			fi
-        		elif [[ "$resposta" = '6' ]]; then
+        		elif [[ "$resposta" = '7' ]]; then
 			if ps x | grep -w wsproxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
 				clear
 				msgsocks=$(cat /etc/SSHPlus/wsproxy.py | grep -E "MSG =" | awk -F = '{print $2}' | cut -d "'" -f 2)
